### ISSUE TITLE
VersionConflict: (apispec 4.2.0 (c:\python\python38-64\lib\site-packages), Requirement.parse('apispec[yaml]<4,>=3.3'))

### ISSUE THREAD

**Issue by m986883511** [greyli/apiflask#136]
C:\Users\chao\Documents\PROJECTS\python>flask run --reload
Traceback (most recent call last):
  File "c:\python\python38-64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python38-64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python38-64\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "c:\python\python38-64\lib\site-packages\flask\cli.py", line 990, in main
    cli.main(args=sys.argv[1:])
  File "c:\python\python38-64\lib\site-packages\flask\cli.py", line 596, in main
    return super().main(*args, **kwargs)
  File "c:\python\python38-64\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python\python38-64\lib\site-packages\click\core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "c:\python\python38-64\lib\site-packages\click\core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "c:\python\python38-64\lib\site-packages\flask\cli.py", line 539, in get_command
    self._load_plugin_commands()
  File "c:\python\python38-64\lib\site-packages\flask\cli.py", line 535, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "c:\python\python38-64\lib\site-packages\pkg_resources\__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "c:\python\python38-64\lib\site-packages\pkg_resources\__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "c:\python\python38-64\lib\site-packages\pkg_resources\__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (apispec 4.2.0 (c:\python\python38-64\lib\site-packages), Requirement.parse('apispec[yaml]<4,>=3.3'))

能提供一下requeirments.txt吗，我在3.8上测试不过，包冲突，重新安装apispec，你的程序报得大于4.2.0

**Comment by greyli** [comment]
Hi, could you list all the dependencies your project use? APIFlask requires apispec >= 4.2.0, while some library you installed requires apispec[yaml]<4,>=3.3.

I would recommend always creating a virtual environment for every project so that you can prevent version conflict from different projects.
