### ISSUE TITLE
Can't get static files work in version 0.6.1

### ISSUE THREAD

**Issue by z-t-y** [greyli/apiflask#52]
Can't get static files work in version 0.6.1

Example:
```python
from apiflask import APIFlask
app = APIFlask(__name__)

@app.route("/")
def index():
    return ""
```

```css
h1 { font-size: 16px; }
```

File Tree:
```
/app-root
  app.py
  /static
    style.css
```

And I `GET` `/static/style.css` in the browser, I expected to see:
```
h1 { font-size: 16px; }
```
But I got
```
500 Internal Server Error
```

What I have tried
1. Change APIFlask to Flask, it works well.
2. Change to any older version of APIFlask, it doesn't work.

Environment:

- Python version: 3.8.5
- Flask version: 2.0.0
- APIFlask version: 0.6.1

**Comment by greyli** [comment]
I can't reproduce this issue, could you share the error traceback in the terminal output?

**Comment by z-t-y** [comment]
```
[2021-05-16 21:58:11,808] ERROR in app: Exception on /static/style.css [GET]
Traceback (most recent call last):
  File "/home/andyzhou/.local/share/virtualenvs/apiflask_demo-YckP4HEx/lib/python3.8/site-packages/flask/app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andyzhou/.local/share/virtualenvs/apiflask_demo-YckP4HEx/lib/python3.8/site-packages/flask/app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andyzhou/.local/share/virtualenvs/apiflask_demo-YckP4HEx/lib/python3.8/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andyzhou/.local/share/virtualenvs/apiflask_demo-YckP4HEx/lib/python3.8/site-packages/apiflask/app.py", line 128, in dispatch_request
    return self.view_functions[rule.endpoint](*req.view_args.values())
TypeError: <lambda>() takes 0 positional arguments but 1 was given
127.0.0.1 - - [16/May/2021 21:58:11] "GET /static/style.css HTTP/1.1" 500 -
```

**Comment by greyli** [comment]
Got it, I will fix it tomorrow then make a new release. Thanks!
